// <auto-generated />
namespace Celler.Infraestrutura.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alterartipodecharparastring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterartipodecharparastring));
        
        string IMigrationMetadata.Id
        {
            get { return "201707090733088_alterar tipo de char para string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
